### ISSUE TITLE
Issues with multiplayer

### ISSUE THREAD

**Issue by MuniiPanda** [Jbleezy/BO1-Reimagined#11]
I know this may be a longshot since BO1 is pm dead at this point, but me and my boyfriend are attempting to play and we get stuck at "Waiting for other players..." before it eventually kicks him and says lost connection. We live in the same house and use the same WiFi, so I have no idea how this could be happening. Any help is greatly appreciated

**Comment by Jbleezy** [comment]
Verify the integrity of game files on Steam, and make sure you are both on the same game_mod version and Reimagined version.

**Comment by WhatATopic** [comment]
Is there anything else that I can do to fix this issue? I am having the same problem and we have already verified integrity of game files for both single player and multiplayer and we are using the same version of game_mod and reimagined. The game works fine normally but I would love to play with this mod.

**Comment by Jbleezy** [comment]
It should work if you are sure all of that is correct.

**Comment by WhatATopic** [comment]
The only thing that I noticed was when verifying integrity of game files, it says 1 file failed to validate and will be reacquired. Then if I verify integrity again, it continues to say the same thing. I checked steam logs and the file that is failing to verify is the blackops.exe. I checked the date modified for the file and everytime I verify integrity, it is updating so I'm not sure why it keeps failing. Maybe this is why the mod is not working?

**Comment by Jbleezy** [comment]
Yeah that's probably it. Are you using the official Steam version of BO1?

**Comment by WhatATopic** [comment]
Yes my friend and I are both using the official steam version and we are both getting the 1 file failed to validate. If you verify integrity, does it give you the same message?

**Comment by Jbleezy** [comment]
No I would always get no files failed.

**Comment by WhatATopic** [comment]
I solved the problem. My friend and I both had the game installed on a secondary hard drive but when we moved the game to our C drive, we could actually play. Could the mod be checking the C drive for game files during the map load process?

**Comment by Jbleezy** [comment]
It could be, possibly a game_mod issue.
