### ISSUE TITLE
Cz75 (Dual Wield) No Sound on right side pistol

### ISSUE THREAD

**Issue by Rockythelover22** [Jbleezy/BO1-Reimagined#18]

**Comment by Rockythelover22** [comment]
I'm currently playing Der Riese with this mod on but I get the dual CZ75 pistols out of the box, upon firing there is quiet right side pistol all my sounds are maxed out and I can hear things normal left side has no issues on sound.

https://user-images.githubusercontent.com/87906365/176785586-9ab4a4d4-b660-4da6-bbf0-367970fc01ab.mp4

**Comment by Jbleezy** [comment]
I just tested it, sounds fine to me.
