### ISSUE TITLE
Console comands

### ISSUE THREAD

**Issue by Ronpeduros** [Jbleezy/BO1-Reimagined#19]
Hey , IK I am probably to late here but , I love this mod , probably the best one , I was trying to do the ester egg on shangrila to have the stone so I can do the moon ester egg to do it with people that doesn’t want to put mods in theirs game ,  is that posible to enable commands so it will be more easy to do it?  Or if there is a other way to get the ester egg without the need of 4 players?

**Comment by Jbleezy** [comment]
All sidequests are completable with any amount of players.
