### ISSUE TITLE
The mod doesn't load 

### ISSUE THREAD

**Issue by 7ajykrock** [Jbleezy/BO1-Reimagined#20]
when i downloaded it i tried to unzip it with winRAR but it said it was corrupted so i tried to with 7zip and it worked but not all the files were in the folder some of the files that are shown in this website didn't apear + when i used the game mod file to add modes onto my steam version of bo1 the mods section showed up on the tv i selected reimagined and after loading it and playing the game nothing changed no new settings nor can i finish the EEs solo and i tried it also with plutonium  i created a mods folder in plutonium and and dragged the mod into it and started the game loaded the mod and again nothing changed so i believe it's cuz the file didn't download fully i redownloaded it many times but it never seems to work , any suggestions ?

**Comment by Jbleezy** [comment]
Try using the exe.
