### ISSUE TITLE
Issue with shortcut

### ISSUE THREAD

**Issue by HumanYeeeee** [Jbleezy/BO1-Reimagined#22]
So I use plutonium, I did everything right (or I hope I did), and I did what you said at the end to fix the shortcut issues "Right click on BO_Reimagined.bat, then select Copy. Right click on Call of Duty Black Ops (Reimagined) shortcut, then select Properties. Select Target, then press CTRL + V, then click OK." problem is, now it says the folder C:/program files (x86)/steamapps bluh bluh bluh, is not valid in the "start in" section in properties, what do I do?

**Comment by Jbleezy** [comment]
It doesn't work with Plutonium.
