### ISSUE TITLE
Possibility to edit certain changes? 

### ISSUE THREAD

**Issue by sleepyzer0** [Jbleezy/BO1-Reimagined#23]
I was wondering if it's possible to revert some things like bring back the og mystery box light for Shi No Numa (and lack thereof for Nacht/Verukt), remove the added/reduced sprint speed of some weapons, etc. I love this mod so much but I find some changes to be of personal preference rather than "quality of life" in my opinion. I can't open some of the archived folders inside the mod to see what all I can change so not sure if that's intentional or not. Much love and thanks for all you do.

**Comment by Jbleezy** [comment]
Fork this repo and use the BO1 mod tools to make your changes.

**Comment by Clev7** [comment]
> Fork this repo and use the BO1 mod tools to make your changes.

Sorry if I sound like I'm asking too much. I have a background in software development but not in mod development, but could you elaborate on how to go about making those changes?
