### ISSUE TITLE
Hosting Issues With BO1 Reimagined 

### ISSUE THREAD

**Issue by Antonio115GH** [Jbleezy/BO1-Reimagined#24]
Hello JBeelzy this is the Antonio Beta Testing guy, from WAW Zombies Remaster by JB-Shady. This will be a informal bug report mainly because, I am asking for any troubleshooting options. When hosting your mod online in a private match with friends.

So last night, a friend and I were trying to play standard survival on your mod. Despite successfully hosting multiple matches of vanilla BO1 Zombies, on the mod launcher beforehand. We could not host a match in your mod. (We were stuck at the loading screen, with the loading text stuck on awaiting players). We tried playing Five and Der Riese. Here I will list some things that I think could of caused the issue/we did not try to fix the issue. I get this is funny haha issue, with a hosting problem that everyone could have. So you probably can't do much. But I figure I give this a shot.

- My friend was new player to the mod. So maybe something config was not setup right. (Don't think this is actual issue, since the host's config of the match determines the gamemode and other things). 
- Did not have him host.
- I did not deactivate my custom texture for BO1 Vanilla/Vanilla + Modded Gameplay 
- Did not try the other maps.

So yeah sorry, if this is lackluster not really important report. Although, if you had any suggestions on what to do I would appreciate it. If not no worries.

**Comment by Jbleezy** [comment]
Make sure you all have the mod loaded and are on the same version.
