### ISSUE TITLE
Need detailed help to install the mod (Thanks in advance Jbleezy)

### ISSUE THREAD

**Issue by Romdy02** [Jbleezy/BO1-Reimagined#25]
Dear @Jbleezy,

First of all, I'd like to salute your work and thank you for all you do for the community.

Please friend, can you give me a detailed end-to-end process to install your BO 1 Reimagined mod that I've been unable to install for several weeks.

I have unzipped the entire BO1-Reimagined folder, which I have copied here %appdata%/Local/Plutonium/t5/mods/->BO1-Reimagined

My t5_plutonium_full game folder is here: E:\Games\t5_pluto_full_game

I've copied the contents of the game_mod zip file into my E:\Games\t5_pluto_full_game folder.

When I launch plutonium and load the mod, I don't see any weapons or other visual textures, and when the game starts on any map, the power is already on and the zoombies are as excited as they were in round 10. I've tried everything, I'm desperate...  I'd also like to point out that I previously installed a menu mod via a patch_zombie.fff file to be replaced, could this cause a problem?

**Comment by Jbleezy** [comment]
BO1 Reimagined does not currently work with Plutonium, use [LinkerMod](https://github.com/Nukem9/LinkerMod) instead.

**Comment by Romdy02** [comment]
Hi JBleezy,

Thank you very mutch for your reply, im gonna use BO 1 from Steam for your Mod. There is any solutions to profit the Reimagined with French language ? And last question, as is possible to reintegrate the Mule Kick on Kino, Five and WAW map's ?  Thank you Legend 🙏

**Comment by Jbleezy** [comment]
You can make a pull request adding French language support. All the localized strings are [here](https://github.com/Jbleezy/BO1-Reimagined/blob/master/localizedstrings/reimagined.str).

Mule Kick is on Kino now, I'm not adding it to the other maps.

**Comment by Romdy02** [comment]
Thank you very mutch. I will start to install BO from Steam and try to use your mod Smoother -_- 

I will text If I encounter difficulties.

Thanks again

**Comment by Romdy02** [comment]
I don't really know what a pull request is.

If I have the game's French files, isn't it possible to simply copy them into the Zone folder?

**Comment by Romdy02** [comment]
Hello again Jbleezy,

I'm a bit pissed lol! 
I just bought Black Ops 1 via this site : 

https://k4g.com/fr/product/call-of-duty-black-ops-steam-global-account-account-37FC3CC8?currency=EUR&r=ppc_FR_pmaxads&utm_source=google&utm_medium=cpc&utm_campaign=pmax&utm_id=18887034162&utm_term=c&utm_content=FR&gad_source=1&gclid=CjwKCAiA1fqrBhA1EiwAMU5m_xS-QtwDClX-8Xz6eFN6TPJuwZ3HlWiMl8I6dYJ4M-qwj98C3SY1RRoCXXEQAvD_BwE

Unfortunately, I find that it's just the game and none of the DLC. Despite this, I inform you having been in the game folder, I created a mods folder, I dragged inside the BO1-Reimagined folder, I pasted the contents of the game_mod zip into the root of the BO 1 folder. I run BO_MODS, everything's fine, the game launches, I can load the mod, but I run into the same problems as on plutonium, no visual textures, no weapons, as if the game started on level 10, power on, doors open, zombies herniated like in the high levels... Can you help me?

**Comment by Romdy02** [comment]
Dear Jbleezy,

Everything works, it's great and I thank you sincerely. Last question, is it possible to use a Mod Menu with your Reimagined Mod?

**Comment by Jbleezy** [comment]
I don't think so.
