### ISSUE TITLE
exe fails to launch, saying it can't find launcher_ldr.exe

### ISSUE THREAD

**Issue by walale12** [Jbleezy/BO1-Reimagined#4]
When I try and launch the Black Ops Reimagined exe, I get the below error message 
![image](https://user-images.githubusercontent.com/10388655/73711203-0489d200-46fe-11ea-816e-506f247781f6.png)
The exe is in C:\Program Files (x86)\Steam\steamapps\common\Call of Duty Black Ops. I've tried setting the target to be the .bat file, and even directly launching the .bat as an administrator, but with no luck.

**Comment by walale12** [comment]
Fixed, turns out I'd improperly installed game_mod

**Comment by Jbleezy** [comment]
How did you install game_mod initially and how did you fix it? I've had a lot of people leaving comments on my YouTube videos having the same problem, but wasn't sure exactly what was causing it.

**Comment by walale12** [comment]
Initially I had copied the folder itself to my BO1 directory, I fixed it by
copying the folder's contents to the BO1 directory, not the folder.
