### ISSUE TITLE
[bug] glitches found in versus mode

### ISSUE THREAD

**Issue by absolutestub** [Jbleezy/BO1-Reimagined#7]
https://www.youtube.com/watch?v=DDt_EgeDBOY

**Comment by Jbleezy** [comment]
I don't think there is a way to fix the zombie pathing in the Biodome on Moon.

I will look into the Der Riese teleporter bug.

**Comment by Jbleezy** [comment]
Commit 46c7747af0c22dcb6546831d81010a2a0c76ccb6 fixes the meat powerup.

Commit ac32dad4180ef064c442167ed3156848bbb69d8c fixes the teleporters.

The teleporter respawn "bug" is technically working as intended, since you are out of the map at the teleporter box location and the start room is closer.
